<template>
  <div class="project-create-page">
    <div class="page-header">
      <el-button text @click="$router.push('/projects')">
        <el-icon><ArrowLeft /></el-icon>
        {{ $t('common.back') }}
      </el-button>
      <h1 class="page-title">{{ $t('project.create') }}</h1>
    </div>

    <div class="form-card">
      <el-form
        ref="formRef"
        :model="form"
        :rules="rules"
        label-width="140px"
        label-position="left"
        size="large"
      >
        <el-divider content-position="left">{{ $t('project.projectInfo') }}</el-divider>

        <el-form-item :label="$t('project.name')" prop="name">
          <el-input
            v-model="form.name"
            :placeholder="$t('project.namePlaceholder')"
            @change="autoGenerateCode"
          />
        </el-form-item>

        <el-form-item :label="$t('project.code')">
          <el-input v-model="form.code" disabled>
            <template #append>{{ $t('project.codeAutoGenerated') }}</template>
          </el-input>
        </el-form-item>

        <el-form-item :label="$t('project.productLine')" prop="productLine">
          <el-select
            v-model="form.productLine"
            :placeholder="$t('project.productLinePlaceholder')"
            style="width: 100%"
            @change="autoGenerateCode"
          >
            <el-option v-for="pl in productLines" :key="pl" :label="pl" :value="pl" />
          </el-select>
        </el-form-item>

        <el-form-item :label="$t('project.description')">
          <el-input
            v-model="form.description"
            type="textarea"
            :rows="4"
            :placeholder="$t('project.descriptionPlaceholder')"
          />
        </el-form-item>

        <el-divider content-position="left">{{ $t('dashboard.summary') }}</el-divider>

        <div class="form-row">
          <el-form-item :label="$t('project.startDate')" prop="startDate" style="flex: 1">
            <el-date-picker
              v-model="form.startDate"
              type="date"
              format="YYYY-MM-DD"
              value-format="YYYY-MM-DD"
              style="width: 100%"
            />
          </el-form-item>
          <el-form-item :label="$t('project.endDate')" prop="endDate" style="flex: 1">
            <el-date-picker
              v-model="form.endDate"
              type="date"
              format="YYYY-MM-DD"
              value-format="YYYY-MM-DD"
              style="width: 100%"
            />
          </el-form-item>
        </div>

        <el-form-item :label="$t('project.priority')" prop="priority">
          <el-radio-group v-model="form.priority">
            <el-radio value="high">
              <el-tag type="danger">{{ $t('project.priorities.high') }}</el-tag>
            </el-radio>
            <el-radio value="medium">
              <el-tag type="warning">{{ $t('project.priorities.medium') }}</el-tag>
            </el-radio>
            <el-radio value="low">
              <el-tag type="info">{{ $t('project.priorities.low') }}</el-tag>
            </el-radio>
          </el-radio-group>
        </el-form-item>

        <el-divider content-position="left">{{ $t('project.teamInfo') }}</el-divider>

        <el-form-item :label="$t('project.pm')" prop="pmId">
          <el-select
            v-model="form.pmId"
            :placeholder="$t('project.pmPlaceholder')"
            style="width: 100%"
          >
            <el-option
              v-for="u in pmUsers"
              :key="u.id"
              :label="u.name"
              :value="u.id"
            />
          </el-select>
        </el-form-item>

        <div class="form-row">
          <el-form-item :label="$t('project.rdLocation')" style="flex: 1">
            <el-select v-model="form.rdLocation" style="width: 100%">
              <el-option value="taiwan" :label="$t('project.locations.taiwan')" />
              <el-option value="china" :label="$t('project.locations.china')" />
            </el-select>
          </el-form-item>
          <el-form-item :label="$t('project.mfgLocation')" style="flex: 1">
            <el-select v-model="form.mfgLocation" style="width: 100%">
              <el-option value="taiwan" :label="$t('project.locations.taiwan')" />
              <el-option value="china" :label="$t('project.locations.china')" />
            </el-select>
          </el-form-item>
        </div>

        <div class="form-actions">
          <el-button size="large" @click="$router.push('/projects')">
            {{ $t('common.cancel') }}
          </el-button>
          <el-button type="primary" size="large" :loading="loading" @click="handleSubmit">
            {{ $t('project.create') }}
          </el-button>
        </div>
      </el-form>
    </div>
  </div>
</template>

<script setup>
import { ref } from 'vue'
import { useRouter } from 'vue-router'
import { ElMessage } from 'element-plus'
import { useI18n } from 'vue-i18n'
import { useProjectStore } from '../../../stores/rdm-project.js'
import { PRODUCT_LINES } from '../../../utils/rdm-constants.js'
import { generateProjectCode } from '../../../utils/rdm-helpers.js'
import { DEMO_USERS } from '../../../utils/rdm-demoData.js'

const { t } = useI18n()
const router = useRouter()
const projectStore = useProjectStore()

const loading = ref(false)
const formRef = ref(null)
const productLines = PRODUCT_LINES
const pmUsers = DEMO_USERS.filter((u) => u.role === 'pm' || u.role === 'manager')

const form = ref({
  name: '',
  code: '',
  productLine: 'TGV',
  description: '',
  startDate: '',
  endDate: '',
  priority: 'medium',
  pmId: '',
  rdLocation: 'taiwan',
  mfgLocation: 'china',
  team: [],
})

const rules = {
  name: [{ required: true, message: t('common.required'), trigger: 'blur' }],
  productLine: [{ required: true, message: t('common.required'), trigger: 'change' }],
  pmId: [{ required: true, message: t('common.required'), trigger: 'change' }],
}

function autoGenerateCode() {
  if (form.value.productLine) {
    form.value.code = generateProjectCode(form.value.productLine)
  }
}

async function handleSubmit() {
  if (!formRef.value) return
  try {
    await formRef.value.validate()
    loading.value = true
    if (!form.value.code) {
      form.value.code = generateProjectCode(form.value.productLine)
    }
    const project = projectStore.createProject({ ...form.value })
    ElMessage.success(t('project.createSuccess'))
    router.push(`/projects/${project.id}`)
  } catch (e) {
    // validation failed
  } finally {
    loading.value = false
  }
}
</script>

<style scoped>
.project-create-page {
  max-width: 800px;
}

.page-header {
  display: flex;
  align-items: center;
  gap: 12px;
  margin-bottom: 24px;
}

.page-title {
  font-size: 24px;
  font-weight: 700;
  color: #111827;
}

.form-card {
  background: white;
  border-radius: 16px;
  padding: 32px;
  box-shadow: var(--card-shadow);
  border: 1px solid #e5e7eb;
}

.form-row {
  display: flex;
  gap: 24px;
}

.form-actions {
  display: flex;
  justify-content: flex-end;
  gap: 12px;
  margin-top: 24px;
  padding-top: 24px;
  border-top: 1px solid #e5e7eb;
}
</style>
